### ISSUE TITLE
Create Basic App Structure and Layout

### ISSUE THREAD

**Issue by agabamark** [agabamark/JobHunter#6]
### 1. Create Basic Layout
Create `app/layout.tsx`:
```typescript
import { SpeedInsights } from "@vercel/speed-insights/next"
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "JobHunter",
  description: "Find your next job opportunity",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <SpeedInsights />
      </body>
    </html>
  )
}
```

### 2. Create Home Page
Create `app/page.tsx`:
```typescript
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-4xl font-bold">JobHunter</h1>
      <p className="text-xl">Find your next job opportunity</p>
    </main>
  )
}
```

### 3. Add Global Styles
Create `app/globals.css`:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
```

### 4. Success Criteria
- [ ] Layout renders without errors
- [ ] Home page displays correctly
- [ ] Styles are applied properly
- [ ] Speed Insights is working
